@include('frontend.layout.header')

<div class="inner_sec why_aapl">
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-lg-12">
                <h1> Terms and Condition </h1>
            </div>
        </div>
    </div>
</div>

<div id="breadcrumb">
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-lg-12">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page"> Terms and Condition </li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<div id="smooth-wrapper">
    <div id="smooth-content">
        <div class="container">
            <div class="row justify-content-md-center">
                <div class="col-lg-12">
                    <br /><br />
                    <div class="entry-content">
                        <p>This document is an electronic record in terms of the Information Technology Act, 2000 and
                            rules
                            thereunder
                            as applicable and the amended provisions pertaining to electronic records in various
                            statutes as
                            amended by
                            the Information Technology Act, 2000. This electronic record is generated by a computer
                            system
                            and
                            does not
                            require any physical or digital signatures.</p>

                        <p>The Platform is owned by <strong>AAPL Solutions Private Limited</strong>, a company
                            incorporated
                            under the
                            Indian Companies Act, 1956 with its registered office at <em>[Insert your official address
                                here]</em>
                            (hereinafter referred to as ‘AAPL’).</p>

                        <p>Your use of the Platform and services and tools are governed by the terms and conditions of
                            usage
                            and
                            applicable policies. By mere use of the Platform, you shall be contracting with AAPL and
                            these
                            terms
                            and
                            conditions including the policies constitute your binding obligations with AAPL. For the
                            purpose
                            of
                            these
                            Terms of Use, whenever the context so requires “You” or “User” shall mean any natural or
                            legal
                            person who
                            has agreed to become a user/member on the Platform by providing Registration Data while
                            registering
                            on the
                            Platform as a Registered User using the computer/electronic systems. The terms “We”, “Us”,
                            “Our”
                            shall mean
                            AAPL Solutions Private Limited.</p>

                        <p>Accessing, browsing or otherwise using the site indicates your agreement to all the terms and
                            conditions
                            under these policies so please read the terms carefully before proceeding. By impliedly or
                            expressly
                            accepting these Terms of Use, you also accept and agree to be bound by AAPL Policies
                            (including
                            but
                            not
                            limited to Privacy Policy available at Privacy) as amended from time to time.</p>

                        <h4>Registration Eligibility</h4>
                        <p>Registration on the Platform is available only to persons who can form legally binding
                            contracts
                            under the
                            Indian Contract Act, 1872. Persons who are “incompetent to contract” within the meaning of
                            the
                            Indian
                            Contract Act, 1872 including un-discharged insolvents, etc., are not eligible to use the
                            Platform.
                        </p>

                        <h4>Your Account and Registration Obligations</h4>
                        <p>If you use the Platform, you shall be responsible for maintaining the confidentiality of your
                            Display
                            Name
                            and Password and you shall be responsible for all activities that occur under your Display
                            Name
                            and
                            Password. You agree that if you provide any information that is untrue, inaccurate, not
                            current
                            or
                            incomplete or we have reasonable grounds to suspect that such information is untrue,
                            inaccurate,
                            not
                            current
                            or incomplete or not in accordance with these Terms of Use, we shall have the right to
                            indefinitely
                            suspend
                            or terminate or block access of your registration on the Platform and refuse to provide you
                            with
                            access to
                            the Platform.</p>

                        <p>Your mobile phone number and/or e-mail address is treated as your primary identifier on the
                            Platform.
                            It is
                            your responsibility to ensure that your mobile phone number and your email address are up to
                            date on
                            the
                            Platform at all times. You agree to notify us promptly if your mobile phone number or e-mail
                            address
                            changes
                            by updating the same on the Platform through a one-time password verification.</p>

                        <p>If you share or allow others to have access to your account on the Platform (Account), by
                            creating
                            separate
                            profiles under your account, or otherwise, they will be able to view and access your account
                            information.
                            You shall be solely liable and responsible for all the activities undertaken under your
                            Account
                            and
                            any
                            consequences therefrom.</p>

                        <p>You must maintain confidentiality of the account information and for all the activities that
                            occur
                            under your
                            account. You must not share your login details i.e., username and password of your account
                            with
                            any
                            other
                            person else it would be considered a breach of these Terms of Use. You will have access to
                            the
                            website and
                            other channels of AAPL through the same login username and password.</p>

                        <p>At no time shall AAPL hold any right, title, or interest over the products/gifts nor shall
                            AAPL
                            have
                            any
                            obligations or liabilities in respect of such contract.</p>

                        <p>AAPL is not responsible for unsatisfactory or delayed performance of services or damages or
                            delays as
                            a
                            result of products which are out of stock, unavailable or back ordered.</p>

                        <p>You shall independently agree upon the manner and terms and conditions of delivery, payment,
                            insurance etc.
                            with the seller(s) that you transact with.</p>

                        <h4>Restrictions and Conduct</h4>
                        <p>You shall not make any negative, denigrating or defamatory statement(s) or comment(s) about
                            us or
                            otherwise
                            engage in any conduct or action that might tarnish the image or reputation of AAPL on the
                            platform
                            or
                            otherwise tarnish or dilute any AAPL’s trade or service marks, trade name and/or goodwill
                            associated
                            with
                            such trade or service marks, trade name as may be owned or used by us. You agree not to use
                            any
                            device,
                            software or routine to interfere or attempt to interfere with the proper working of the
                            Platform
                            or
                            any
                            transaction being conducted on the platform, or with any other person’s use of the Platform.
                        </p>

                        <p>You may not use the Platform or any content for any purpose that is unlawful or prohibited by
                            these
                            Terms of
                            Use, or to solicit the performance of any illegal activity or other activity which infringes
                            the
                            rights of
                            AAPL and/or others.</p>

                        <h4>Content Monitoring</h4>
                        <p>We reserve the right to monitor the material posted on the platform. AAPL shall have the
                            right to
                            remove or
                            edit any content that in its sole discretion violates, or is alleged to violate, any
                            applicable
                            law
                            or
                            either the spirit or letter of these Terms of Use. Notwithstanding this right, you remain
                            solely
                            responsible
                            for the content you post on the platform and in your private messages. Please be advised
                            that
                            such
                            content
                            posted does not necessarily reflect AAPL views. In no event shall AAPL assume or have any
                            responsibility or
                            liability for any content posted or for any claims, damages or losses resulting from use of
                            content
                            and/or
                            appearance of content on the platform.</p>

                        <h4>Language & Translations</h4>
                        <p>You acknowledge and agree that the Hindi and English translation features are made available
                            on
                            the
                            Platform
                            on a reasonable effort basis for convenience only, without any representation or warranties
                            by
                            AAPL,
                            express
                            or implied, including the translations being error-free, their accuracy, completeness or
                            reliability. Some
                            features and sections on the platform may not be translated in the language selected by you
                            (Hindi),
                            and the
                            English version of the same will be the definitive version. In the event of any conflict or
                            inconsistency
                            between the translated terms and the English version available on the Platform, the English
                            version
                            on the
                            Platform shall prevail. AAPL reserves the right to change, enhance, suspend, or discontinue
                            this
                            feature, or
                            any part of it, at any time without notice to you.</p>
                    </div>
                </div>
            </div>
        </div>
        @include('frontend.layout.client')
        @include('frontend.layout.footer')
    </div>
</div>